### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by NigelKibodeaux**
It occurs to me now that there is no reason for this to be a fork of airbnb's javascript repo anymore. maybe we should move this to its own repo (named something more obvious).

Anyway, here are some proposed tweaks to what you had. The commit comments explain what I was doing.

### CODE REVIEW

**Comment by carterbancroft** [comment]
@NigelKibodeaux that sounds good to me. I don't have the privileges, but if you want create a new repo I can just move things over to that. Maybe me-styleguide or something?

**Comment by NigelKibodeaux** [comment]
okey dokey here you go: https://github.com/aboutdotme/me-node-lint

**Comment by NigelKibodeaux** [comment]
We don't need this anymore for backend stuff but @pascalpp wants to keep just the README around in this repo as a reference.

**Comment by carterbancroft** [comment]
Thank ya sir. I added most of the key stuff to master in me-node-lint, I'm not sure if it needs any special setup on the npm side to do a release or what.

**Comment by NigelKibodeaux** [comment]
I don't think so, I think just `npm publish` will do it.

**Pull request closed without merging**
